### ISSUE TITLE
Running behind reverse proxy

### ISSUE THREAD

**Issue by Ineluki** [SemanticComputing/fuseki-docker#26]
I'm trying to find a way to run the fuseki container behind a reverse proxy and subsequent base-path (e.g. http://example.com/fuseki)

The apache docs describe it as `fuseki-server [--loc=DIR] [[--update] /NAME]` where NAME is the base-path.

Source: https://jena.apache.org/documentation/fuseki2/fuseki-webapp.html#fuseki-standalone-server

How can I achieve that in the config of this docker container?

**Comment by yoge1** [comment]
You can configure the base name of the Fuseki service by setting the `fuseki:name` property of the `fuseki:Service` in the [assembler file](https://github.com/SemanticComputing/fuseki-docker/blob/master/assembler.ttl#L16).

See more: https://jena.apache.org/documentation/fuseki2/fuseki-configuration.html

**Comment by Myasir92** [comment]
I am running Fuseki on Docker and using Nginx to redirect from `localhost/fuseki` in order to display the UI. While the application starts and functions perfectly, the UI does not load correctly in the browser. This issue arises because requests for HTML and CSS files are sent to `localhost` instead of `localhost/fuseki`. I also tried setting the service name as `localhost/fuseki`, but this approach was unsuccessful. Can you please provide guidance?

**Comment by Myasir92** [comment]
Thanks for your response, @yoge1 . I tried your suggestion, but it didn't work for me. As I mentioned previously, the functionalities of Fuseki work perfectly fine when I send requests directly to the API. The problem occurs only when I try to run it with an Nginx proxy.
